<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities =
            [
                ["state_id" => 1, "name" => "15 مايو"],
                ["state_id" => 1, "name" => "الازبكية"],
                ["state_id" => 1, "name" => "البساتين"],
                ["state_id" => 1, "name" => "التبين"],
                ["state_id" => 1, "name" => "الخليفة"],
                ["state_id" => 1, "name" => "الدراسة"],
                ["state_id" => 1, "name" => "الدرب الاحمر"],
                ["state_id" => 1, "name" => "الزاوية الحمراء"],
                ["state_id" => 1, "name" => "الزيتون"],
                ["state_id" => 1, "name" => "الساحل"],
                ["state_id" => 1, "name" => "السلام"],
                ["state_id" => 1, "name" => "السيدة زينب"],
                ["state_id" => 1, "name" => "الشرابية"],
                ["state_id" => 1, "name" => "مدينة الشروق"],
                ["state_id" => 1, "name" => "الظاهر"],
                ["state_id" => 1, "name" => "العتبة"],
                ["state_id" => 1, "name" => "القاهرة الجديدة"],
                ["state_id" => 1, "name" => "المرج"],
                ["state_id" => 1, "name" => "عزبة النخل"],
                ["state_id" => 1, "name" => "المطرية"],
                ["state_id" => 1, "name" => "المعادى"],
                ["state_id" => 1, "name" => "المعصرة"],
                ["state_id" => 1, "name" => "المقطم"],
                ["state_id" => 1, "name" => "المنيل"],
                ["state_id" => 1, "name" => "الموسكى"],
                ["state_id" => 1, "name" => "النزهة"],
                ["state_id" => 1, "name" => "الوايلى"],
                ["state_id" => 1, "name" => "باب الشعرية"],
                ["state_id" => 1, "name" => "بولاق"],
                ["state_id" => 1, "name" => "جاردن سيتى"],
                ["state_id" => 1, "name" => "حدائق القبة"],
                ["state_id" => 1, "name" => "حلوان"],
                ["state_id" => 1, "name" => "دار السلام"],
                ["state_id" => 1, "name" => "شبرا"],
                ["state_id" => 1, "name" => "طره"],
                ["state_id" => 1, "name" => "عابدين"],
                ["state_id" => 1, "name" => "عباسية"],
                ["state_id" => 1, "name" => "عين شمس"],
                ["state_id" => 1, "name" => "مدينة نصر"],
                ["state_id" => 1, "name" => "مصر الجديدة"],
                ["state_id" => 1, "name" => "مصر القديمة"],
                ["state_id" => 1, "name" => "منشية ناصر"],
                ["state_id" => 1, "name" => "مدينة بدر"],
                ["state_id" => 1, "name" => "مدينة العبور"],
                ["state_id" => 1, "name" => "وسط البلد"],
                ["state_id" => 1, "name" => "الزمالك"],
                ["state_id" => 1, "name" => "قصر النيل"],
                ["state_id" => 1, "name" => "الرحاب"],
                ["state_id" => 1, "name" => "القطامية"],
                ["state_id" => 1, "name" => "مدينتي"],
                ["state_id" => 1, "name" => "روض الفرج"],
                ["state_id" => 1, "name" => "شيراتون"],
                ["state_id" => 1, "name" => "الجمالية"],
                ["state_id" => 1, "name" => "العاشر من رمضان"],
                ["state_id" => 1, "name" => "الحلمية"],
                ["state_id" => 1, "name" => "النزهة الجديدة"],
                ["state_id" => 1, "name" => "العاصمة الإدارية"],
                ["state_id" => 2, "name" => "الجيزة"],
                ["state_id" => 2, "name" => "السادس من أكتوبر"],
                ["state_id" => 2, "name" => "الشيخ زايد"],
                ["state_id" => 2, "name" => "الحوامدية"],
                ["state_id" => 2, "name" => "البدرشين"],
                ["state_id" => 2, "name" => "الصف"],
                ["state_id" => 2, "name" => "أطفيح"],
                ["state_id" => 2, "name" => "العياط"],
                ["state_id" => 2, "name" => "الباويطي"],
                ["state_id" => 2, "name" => "منشأة القناطر"],
                ["state_id" => 2, "name" => "أوسيم"],
                ["state_id" => 2, "name" => "كرداسة"],
                ["state_id" => 2, "name" => "أبو النمرس"],
                ["state_id" => 2, "name" => "كفر غطاطي"],
                ["state_id" => 2, "name" => "منشأة البكاري"],
                ["state_id" => 2, "name" => "الدقى"],
                ["state_id" => 2, "name" => "العجوزة"],
                ["state_id" => 2, "name" => "الهرم"],
                ["state_id" => 2, "name" => "الوراق"],
                ["state_id" => 2, "name" => "امبابة"],
                ["state_id" => 2, "name" => "بولاق الدكرور"],
                ["state_id" => 2, "name" => "الواحات البحرية"],
                ["state_id" => 2, "name" => "العمرانية"],
                ["state_id" => 2, "name" => "المنيب"],
                ["state_id" => 2, "name" => "بين السرايات"],
                ["state_id" => 2, "name" => "الكيت كات"],
                ["state_id" => 2, "name" => "المهندسين"],
                ["state_id" => 2, "name" => "فيصل"],
                ["state_id" => 2, "name" => "أبو رواش"],
                ["state_id" => 2, "name" => "حدائق الأهرام"],
                ["state_id" => 2, "name" => "الحرانية"],
                ["state_id" => 2, "name" => "حدائق اكتوبر"],
                ["state_id" => 2, "name" => "صفط اللبن"],
                ["state_id" => 2, "name" => "القرية الذكية"],
                ["state_id" => 2, "name" => "ارض اللواء"],
                ["state_id" => 3, "name" => "ابو قير"],
                ["state_id" => 3, "name" => "الابراهيمية"],
                ["state_id" => 3, "name" => "الأزاريطة"],
                ["state_id" => 3, "name" => "الانفوشى"],
                ["state_id" => 3, "name" => "الدخيلة"],
                ["state_id" => 3, "name" => "السيوف"],
                ["state_id" => 3, "name" => "العامرية"],
                ["state_id" => 3, "name" => "اللبان"],
                ["state_id" => 3, "name" => "المفروزة"],
                ["state_id" => 3, "name" => "المنتزه"],
                ["state_id" => 3, "name" => "المنشية"],
                ["state_id" => 3, "name" => "الناصرية"],
                ["state_id" => 3, "name" => "امبروزو"],
                ["state_id" => 3, "name" => "باب شرق"],
                ["state_id" => 3, "name" => "برج العرب"],
                ["state_id" => 3, "name" => "ستانلى"],
                ["state_id" => 3, "name" => "سموحة"],
                ["state_id" => 3, "name" => "سيدى بشر"],
                ["state_id" => 3, "name" => "شدس"],
                ["state_id" => 3, "name" => "غيط العنب"],
                ["state_id" => 3, "name" => "فلمينج"],
                ["state_id" => 3, "name" => "فيكتوريا"],
                ["state_id" => 3, "name" => "كامب شيزار"],
                ["state_id" => 3, "name" => "كرموز"],
                ["state_id" => 3, "name" => "محطة الرمل"],
                ["state_id" => 3, "name" => "مينا البصل"],
                ["state_id" => 3, "name" => "العصافرة"],
                ["state_id" => 3, "name" => "العجمي"],
                ["state_id" => 3, "name" => "بكوس"],
                ["state_id" => 3, "name" => "بولكلي"],
                ["state_id" => 3, "name" => "كليوباترا"],
                ["state_id" => 3, "name" => "جليم"],
                ["state_id" => 3, "name" => "المعمورة"],
                ["state_id" => 3, "name" => "المندرة"],
                ["state_id" => 3, "name" => "محرم بك"],
                ["state_id" => 3, "name" => "الشاطبي"],
                ["state_id" => 3, "name" => "سيدي جابر"],
                ["state_id" => 3, "name" => "الساحل الشمالي"],
                ["state_id" => 3, "name" => "الحضرة"],
                ["state_id" => 3, "name" => "العطارين"],
                ["state_id" => 3, "name" => "سيدي كرير"],
                ["state_id" => 3, "name" => "الجمرك"],
                ["state_id" => 3, "name" => "المكس"],
                ["state_id" => 3, "name" => "مارينا"],
                ["state_id" => 4, "name" => "المنصورة"],
                ["state_id" => 4, "name" => "طلخا"],
                ["state_id" => 4, "name" => "ميت غمر"],
                ["state_id" => 4, "name" => "دكرنس"],
                ["state_id" => 4, "name" => "أجا"],
                ["state_id" => 4, "name" => "منية النصر"],
                ["state_id" => 4, "name" => "السنبلاوين"],
                ["state_id" => 4, "name" => "الكردي"],
                ["state_id" => 4, "name" => "بني عبيد"],
                ["state_id" => 4, "name" => "المنزلة"],
                ["state_id" => 4, "name" => "تمي الأمديد"],
                ["state_id" => 4, "name" => "الجمالية"],
                ["state_id" => 4, "name" => "شربين"],
                ["state_id" => 4, "name" => "المطرية"],
                ["state_id" => 4, "name" => "بلقاس"],
                ["state_id" => 4, "name" => "ميت سلسيل"],
                ["state_id" => 4, "name" => "جمصة"],
                ["state_id" => 4, "name" => "محلة دمنة"],
                ["state_id" => 4, "name" => "نبروه"],
                ["state_id" => 5, "name" => "الغردقة"],
                ["state_id" => 5, "name" => "رأس غارب"],
                ["state_id" => 5, "name" => "سفاجا"],
                ["state_id" => 5, "name" => "القصير"],
                ["state_id" => 5, "name" => "مرسى علم"],
                ["state_id" => 5, "name" => "الشلاتين"],
                ["state_id" => 5, "name" => "حلايب"],
                ["state_id" => 5, "name" => "الدهار"],
                ["state_id" => 6, "name" => "دمنهور"],
                ["state_id" => 6, "name" => "كفر الدوار"],
                ["state_id" => 6, "name" => "رشيد"],
                ["state_id" => 6, "name" => "إدكو"],
                ["state_id" => 6, "name" => "أبو المطامير"],
                ["state_id" => 6, "name" => "أبو حمص"],
                ["state_id" => 6, "name" => "الدلنجات"],
                ["state_id" => 6, "name" => "المحمودية"],
                ["state_id" => 6, "name" => "الرحمانية"],
                ["state_id" => 6, "name" => "إيتاي البارود"],
                ["state_id" => 6, "name" => "حوش عيسى"],
                ["state_id" => 6, "name" => "شبراخيت"],
                ["state_id" => 6, "name" => "كوم حمادة"],
                ["state_id" => 6, "name" => "بدر"],
                ["state_id" => 6, "name" => "وادي النطرون"],
                ["state_id" => 6, "name" => "النوبارية الجديدة"],
                ["state_id" => 6, "name" => "النوبارية"],
                ["state_id" => 7, "name" => "الفيوم"],
                ["state_id" => 7, "name" => "الفيوم الجديدة"],
                ["state_id" => 7, "name" => "طامية"],
                ["state_id" => 7, "name" => "سنورس"],
                ["state_id" => 7, "name" => "إطسا"],
                ["state_id" => 7, "name" => "إبشواي"],
                ["state_id" => 7, "name" => "يوسف الصديق"],
                ["state_id" => 7, "name" => "الحادقة"],
                ["state_id" => 7, "name" => "اطسا"],
                ["state_id" => 7, "name" => "الجامعة"],
                ["state_id" => 7, "name" => "السيالة"],
                ["state_id" => 8, "name" => "طنطا"],
                ["state_id" => 8, "name" => "المحلة الكبرى"],
                ["state_id" => 8, "name" => "كفر الزيات"],
                ["state_id" => 8, "name" => "زفتى"],
                ["state_id" => 8, "name" => "السنطة"],
                ["state_id" => 8, "name" => "قطور"],
                ["state_id" => 8, "name" => "بسيون"],
                ["state_id" => 8, "name" => "سمنود"],
                ["state_id" => 9, "name" => "الإسماعيلية"],
                ["state_id" => 9, "name" => "فايد"],
                ["state_id" => 9, "name" => "القنطرة شرق"],
                ["state_id" => 9, "name" => "القنطرة غرب"],
                ["state_id" => 9, "name" => "التل الكبير"],
                ["state_id" => 9, "name" => "أبو صوير"],
                ["state_id" => 9, "name" => "القصاصين الجديدة"],
                ["state_id" => 9, "name" => "نفيشة"],
                ["state_id" => 9, "name" => "الشيخ زايد"],
                ["state_id" => 10, "name" => "شبين الكوم"],
                ["state_id" => 10, "name" => "مدينة السادات"],
                ["state_id" => 10, "name" => "منوف"],
                ["state_id" => 10, "name" => "سرس الليان"],
                ["state_id" => 10, "name" => "أشمون"],
                ["state_id" => 10, "name" => "الباجور"],
                ["state_id" => 10, "name" => "قويسنا"],
                ["state_id" => 10, "name" => "بركة السبع"],
                ["state_id" => 10, "name" => "تلا"],
                ["state_id" => 10, "name" => "الشهداء"],
                ["state_id" => 11, "name" => "المنيا"],
                ["state_id" => 11, "name" => "المنيا الجديدة"],
                ["state_id" => 11, "name" => "العدوة"],
                ["state_id" => 11, "name" => "مغاغة"],
                ["state_id" => 11, "name" => "بني مزار"],
                ["state_id" => 11, "name" => "مطاي"],
                ["state_id" => 11, "name" => "سمالوط"],
                ["state_id" => 11, "name" => "المدينة الفكرية"],
                ["state_id" => 11, "name" => "ملوي"],
                ["state_id" => 11, "name" => "دير مواس"],
                ["state_id" => 11, "name" => "ابو قرقاص"],
                ["state_id" => 11, "name" => "ارض سلطان"],
                ["state_id" => 12, "name" => "بنها"],
                ["state_id" => 12, "name" => "قليوب"],
                ["state_id" => 12, "name" => "شبرا الخيمة"],
                ["state_id" => 12, "name" => "القناطر الخيرية"],
                ["state_id" => 12, "name" => "الخانكة"],
                ["state_id" => 12, "name" => "كفر شكر"],
                ["state_id" => 12, "name" => "طوخ"],
                ["state_id" => 12, "name" => "قها"],
                ["state_id" => 12, "name" => "العبور"],
                ["state_id" => 12, "name" => "الخصوص"],
                ["state_id" => 12, "name" => "شبين القناطر"],
                ["state_id" => 12, "name" => "مسطرد"],
                ["state_id" => 13, "name" => "الخارجة"],
                ["state_id" => 13, "name" => "باريس"],
                ["state_id" => 13, "name" => "موط"],
                ["state_id" => 13, "name" => "الفرافرة"],
                ["state_id" => 13, "name" => "بلاط"],
                ["state_id" => 13, "name" => "الداخلة"],
                ["state_id" => 14, "name" => "السويس"],
                ["state_id" => 14, "name" => "الجناين"],
                ["state_id" => 14, "name" => "عتاقة"],
                ["state_id" => 14, "name" => "العين السخنة"],
                ["state_id" => 14, "name" => "فيصل"],
                ["state_id" => 15, "name" => "أسوان"],
                ["state_id" => 15, "name" => "أسوان الجديدة"],
                ["state_id" => 15, "name" => "دراو"],
                ["state_id" => 15, "name" => "كوم أمبو"],
                ["state_id" => 15, "name" => "نصر النوبة"],
                ["state_id" => 15, "name" => "كلابشة"],
                ["state_id" => 15, "name" => "إدفو"],
                ["state_id" => 15, "name" => "الرديسية"],
                ["state_id" => 15, "name" => "البصيلية"],
                ["state_id" => 15, "name" => "السباعية"],
                ["state_id" => 15, "name" => "ابوسمبل السياحية"],
                ["state_id" => 15, "name" => "مرسى علم"],
                ["state_id" => 16, "name" => "أسيوط"],
                ["state_id" => 16, "name" => "أسيوط الجديدة"],
                ["state_id" => 16, "name" => "ديروط"],
                ["state_id" => 16, "name" => "منفلوط"],
                ["state_id" => 16, "name" => "القوصية"],
                ["state_id" => 16, "name" => "أبنوب"],
                ["state_id" => 16, "name" => "أبو تيج"],
                ["state_id" => 16, "name" => "الغنايم"],
                ["state_id" => 16, "name" => "ساحل سليم"],
                ["state_id" => 16, "name" => "البداري"],
                ["state_id" => 16, "name" => "صدفا"],
                ["state_id" => 17, "name" => "بني سويف"],
                ["state_id" => 17, "name" => "بني سويف الجديدة"],
                ["state_id" => 17, "name" => "الواسطى"],
                ["state_id" => 17, "name" => "ناصر"],
                ["state_id" => 17, "name" => "إهناسيا"],
                ["state_id" => 17, "name" => "ببا"],
                ["state_id" => 17, "name" => "الفشن"],
                ["state_id" => 17, "name" => "سمسطا"],
                ["state_id" => 17, "name" => "الاباصيرى"],
                ["state_id" => 17, "name" => "مقبل"],
                ["state_id" => 18, "name" => "بورسعيد"],
                ["state_id" => 18, "name" => "بورفؤاد"],
                ["state_id" => 18, "name" => "العرب"],
                ["state_id" => 18, "name" => "حى الزهور"],
                ["state_id" => 18, "name" => "حى الشرق"],
                ["state_id" => 18, "name" => "حى الضواحى"],
                ["state_id" => 18, "name" => "حى المناخ"],
                ["state_id" => 18, "name" => "حى مبارك"],
                ["state_id" => 19, "name" => "دمياط"],
                ["state_id" => 19, "name" => "دمياط الجديدة"],
                ["state_id" => 19, "name" => "رأس البر"],
                ["state_id" => 19, "name" => "فارسكور"],
                ["state_id" => 19, "name" => "الزرقا"],
                ["state_id" => 19, "name" => "السرو"],
                ["state_id" => 19, "name" => "الروضة"],
                ["state_id" => 19, "name" => "كفر البطيخ"],
                ["state_id" => 19, "name" => "عزبة البرج"],
                ["state_id" => 19, "name" => "ميت أبو غالب"],
                ["state_id" => 19, "name" => "كفر سعد"],
                ["state_id" => 20, "name" => "الزقازيق"],
                ["state_id" => 20, "name" => "العاشر من رمضان"],
                ["state_id" => 20, "name" => "منيا القمح"],
                ["state_id" => 20, "name" => "بلبيس"],
                ["state_id" => 20, "name" => "مشتول السوق"],
                ["state_id" => 20, "name" => "القنايات"],
                ["state_id" => 20, "name" => "أبو حماد"],
                ["state_id" => 20, "name" => "القرين"],
                ["state_id" => 20, "name" => "ههيا"],
                ["state_id" => 20, "name" => "أبو كبير"],
                ["state_id" => 20, "name" => "فاقوس"],
                ["state_id" => 20, "name" => "الصالحية الجديدة"],
                ["state_id" => 20, "name" => "الإبراهيمية"],
                ["state_id" => 20, "name" => "ديرب نجم"],
                ["state_id" => 20, "name" => "كفر صقر"],
                ["state_id" => 20, "name" => "أولاد صقر"],
                ["state_id" => 20, "name" => "الحسينية"],
                ["state_id" => 20, "name" => "صان الحجر القبلية"],
                ["state_id" => 20, "name" => "منشأة أبو عمر"],
                ["state_id" => 21, "name" => "الطور"],
                ["state_id" => 21, "name" => "شرم الشيخ"],
                ["state_id" => 21, "name" => "دهب"],
                ["state_id" => 21, "name" => "نويبع"],
                ["state_id" => 21, "name" => "طابا"],
                ["state_id" => 21, "name" => "سانت كاترين"],
                ["state_id" => 21, "name" => "أبو رديس"],
                ["state_id" => 21, "name" => "أبو زنيمة"],
                ["state_id" => 21, "name" => "رأس سدر"],
                ["state_id" => 22, "name" => "كفر الشيخ"],
                ["state_id" => 22, "name" => "وسط البلد كفر الشيخ"],
                ["state_id" => 22, "name" => "دسوق"],
                ["state_id" => 22, "name" => "فوه"],
                ["state_id" => 22, "name" => "مطوبس"],
                ["state_id" => 22, "name" => "برج البرلس"],
                ["state_id" => 22, "name" => "بلطيم"],
                ["state_id" => 22, "name" => "مصيف بلطيم"],
                ["state_id" => 22, "name" => "الحامول"],
                ["state_id" => 22, "name" => "بيلا"],
                ["state_id" => 22, "name" => "الرياض"],
                ["state_id" => 22, "name" => "سيدي سالم"],
                ["state_id" => 22, "name" => "قلين"],
                ["state_id" => 22, "name" => "سيدي غازي"],
                ["state_id" => 23, "name" => "مرسى مطروح"],
                ["state_id" => 23, "name" => "الحمام"],
                ["state_id" => 23, "name" => "العلمين"],
                ["state_id" => 23, "name" => "الضبعة"],
                ["state_id" => 23, "name" => "النجيلة"],
                ["state_id" => 23, "name" => "سيدي براني"],
                ["state_id" => 23, "name" => "السلوم"],
                ["state_id" => 23, "name" => "سيوة"],
                ["state_id" => 23, "name" => "مارينا"],
                ["state_id" => 23, "name" => "الساحل الشمالى"],
                ["state_id" => 24, "name" => "الأقصر"],
                ["state_id" => 24, "name" => "الأقصر الجديدة"],
                ["state_id" => 24, "name" => "إسنا"],
                ["state_id" => 24, "name" => "طيبة الجديدة"],
                ["state_id" => 24, "name" => "الزينية"],
                ["state_id" => 24, "name" => "البياضية"],
                ["state_id" => 24, "name" => "القرنة"],
                ["state_id" => 24, "name" => "أرمنت"],
                ["state_id" => 24, "name" => "الطود"],
                ["state_id" => 25, "name" => "قنا"],
                ["state_id" => 25, "name" => "قنا الجديدة"],
                ["state_id" => 25, "name" => "ابو طشت"],
                ["state_id" => 25, "name" => "نجع حمادي"],
                ["state_id" => 25, "name" => "دشنا"],
                ["state_id" => 25, "name" => "الوقف"],
                ["state_id" => 25, "name" => "قفط"],
                ["state_id" => 25, "name" => "نقادة"],
                ["state_id" => 25, "name" => "فرشوط"],
                ["state_id" => 25, "name" => "قوص"],
                ["state_id" => 26, "name" => "العريش"],
                ["state_id" => 26, "name" => "الشيخ زويد"],
                ["state_id" => 26, "name" => "نخل"],
                ["state_id" => 26, "name" => "رفح"],
                ["state_id" => 26, "name" => "بئر العبد"],
                ["state_id" => 26, "name" => "الحسنة"],
                ["state_id" => 27, "name" => "سوهاج"],
                ["state_id" => 27, "name" => "سوهاج الجديدة"],
                ["state_id" => 27, "name" => "أخميم"],
                ["state_id" => 27, "name" => "أخميم الجديدة"],
                ["state_id" => 27, "name" => "البلينا"],
                ["state_id" => 27, "name" => "المراغة"],
                ["state_id" => 27, "name" => "المنشأة"],
                ["state_id" => 27, "name" => "دار السلام"],
                ["state_id" => 27, "name" => "جرجا"],
                ["state_id" => 27, "name" => "جهينة الغربية"],
                ["state_id" => 27, "name" => "ساقلته"],
                ["state_id" => 27, "name" => "طما"],
                ["state_id" => 27, "name" => "طهطا"],
                ["state_id" => 27, "name" => "الكوثر"],
            ];

        foreach ($cities as &$c) {
            $c['created_at'] = now();
        }

        City::insert($cities);
    }
}
