[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=0
pidfile=/run/supervisord.pid


[program:laravel-websocket]
process_name=%(program_name)s_%(process_num)02d
command=php artisan reverb:start --debug
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=ma7lola
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/laravel-websocket.log
stopwaitsecs=3600
minfds=10000