version: '3'
services:
    app:
        build:
            context: .
            dockerfile: docker/production/php/Dockerfile
            args:
                - UID=${UID}
                - GID=${GID}
        image: ma7lola:production-latest
        container_name: app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            # - ma7lola-storage:/var/www/html/storage
        networks:
            - ma7lola
        depends_on:
            - mysql
        command: /usr/bin/supervisord -c /etc/supervisor/conf.d/php-fpm.conf

    workers:
        image: ma7lola:production-latest
        container_name: workers
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            # - ma7lola-storage:/var/www/html/storage
        networks:
            - ma7lola
        depends_on:
            - app
        command: /usr/bin/supervisord -c /etc/supervisor/conf.d/laravel-worker.conf

    nginx:
        build:
            context: .
            dockerfile: docker/production/nginx/Dockerfile
        restart: unless-stopped
        container_name: nginx
        volumes:
            - ./:/var/www/html
            # - ma7lola-storage:/var/www/html/storage
        ports:
            - "80:80"
        networks:
            - ma7lola
        depends_on:
            - mysql
            - app

    mysql:
        image: 'mysql:8.0'
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'ma7lola-mysql:/var/lib/mysql'
        networks:
            - ma7lola
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
        command: --skip-host-cache --skip-name-resolve
      
    redis:
        image: redis:7.2.4
        restart: unless-stopped
        networks:
            - ma7lola

networks:
    ma7lola:
        driver: bridge
volumes:
    ma7lola-mysql:
        driver: local
    ma7lola-storage:
        driver: local